services:
  mongo:
    container_name: GoClean-mongo
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  postgres:
    container_name: GoClean-postgres
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goclean_users
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d goclean_users"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: GoClean-api
    build: ./services/api
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URI: postgresql://root:password@postgres:5432/goclean_users
      MONGO_URI: mongodb://root:password@mongo:27017/goclean?authSource=admin
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    volumes:
      - ./services/api:/app       # hot reload in dev
      - /app/node_modules

  auth:
    container_name: GoClean-auth
    build: ./services/auth
    ports:
      - "5001:5001"
    environment:
      POSTGRES_URI: postgresql://root:password@postgres:5432/goclean_users
      JWT_SECRET: your_jwt_secret
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/auth:/app
      - /app/node_modules

  app:
    container_name: GoClean-app
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost/api

  admin:
    container_name: GoClean-admin
    build: ./admin
    volumes:
      - ./admin:/app
      - /app/node_modules
    environment:
      PUBLIC_URL: /admin
      REACT_APP_API_URL: http://localhost/api

  companies:
    container_name: GoClean-companies
    build: ./services/companies
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/goclean?authSource=admin
      AUTH_SERVICE_URL: http://auth:5001
      NODE_ENV: development
    depends_on:
      - mongo
      - auth
    volumes:
      - ./services/companies:/app
      - /app/node_modules

  reviews:
    container_name: GoClean-reviews
    build: ./services/reviews
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/goclean?authSource=admin
      AUTH_SERVICE_URL: http://auth:5001
      NODE_ENV: development
    depends_on:
      - mongo
      - auth
    volumes:
      - ./services/reviews:/app
      - /app/node_modules

  nginx:
    container_name: GoClean-nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - admin
      - api
      - auth
      - companies
      - reviews

volumes:
  mongo_data:
  postgres_data: