upstream app     { server app:3000; }
upstream admin   { server admin:3001; }
upstream api     { server api:5000; }
upstream auth    { server auth:5001; }

server {
  listen 80;

  location /api/auth/ {
    proxy_pass http://auth/;
  }

  location /api/ {
    proxy_pass http://api/;
  }

  location /admin {
    proxy_pass http://admin;
  }

  location / {
    proxy_pass http://app;
  }
}
