upstream client  { server client:3000; }
upstream api     { server api:5000; }
upstream auth    { server auth:5001; }

server {
  listen 80;

  location /api/auth/ {
    proxy_pass http://auth/;
  }

  location /api/ {
    proxy_pass http://api/;
  }

  location / {
    proxy_pass http://client;
  }
}
